import type { Metadata } from 'next'
import React from 'react'
import { getLocale, getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import ThemeProviderComponent from '@/app/providers/ThemeProviderComponent'
import 'overlayscrollbars/overlayscrollbars.css'
import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'Mark Kappel',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon-mk.ico',
    shortcut: '/favicon-mk.ico',
    apple: '/apple-touch-icon.png'
  }
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProviderComponent>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </ThemeProviderComponent>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
